name: docs

on: [push]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: tool3/docsify-action@master
      with:
        github_token: ${{ secrets.GP_TOKEN }}
        dir: etc/docsify
        # destination branch
        branch: "main"
